# Generated by Django 3.0.3 on 2020-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_enabled', models.BooleanField()),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Bebida', 'Bebidas'), ('Hamburguesa', 'Hamburgesas'), ('Torta', 'Tortas'), ('Postre', 'Postres')], max_length=50)),
            ],
        ),
    ]
