# Generated by Django 3.0.3 on 2020-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
