# Generated by Django 3.0.3 on 2020-07-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
